// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"zoj/internal/http/handler"
	"zoj/internal/http/router"
	"zoj/internal/infra/cache"
	"zoj/internal/infra/database"
	"zoj/internal/infra/llm"
	"zoj/internal/infra/mail"
	"zoj/internal/infra/mq"
	"zoj/internal/infra/redis"
	"zoj/internal/infra/session"
	"zoj/internal/problem/adapter/testdatastore"
	"zoj/internal/repository"
	"zoj/internal/service"
)

// Injectors from wire.go:

func InitHttpServer() (*router.HttpServer, func(), error) {
	db, cleanup := database.NewMysqlClient()
	problemRepo := repository.NewProblemRepo(db)
	submissionRepo := repository.NewSubmissionRepo(db)
	store := testdatastore.New()
	problemService := service.NewProblemService(problemRepo, submissionRepo, store, db)
	problemController := handler.NewProblemController(problemService)
	contestRepo := repository.NewContestRepo(db)
	userRepo := repository.NewUserRepo(db)
	client, cleanup2 := redis.NewRedisClient()
	cacheCache := cache.NewCache(client)
	mqMQ := mq.New(client)
	notificationRepo := repository.NewNotificationRepo(db)
	notificationService := service.NewNotificationService(notificationRepo, userRepo)
	languageRepo := repository.NewLanguageRepo(db)
	languageService := service.NewLanguageService(languageRepo)
	contestService := service.NewContestService(contestRepo, problemRepo, submissionRepo, userRepo, cacheCache, mqMQ, notificationService, store, languageService)
	contestController := handler.NewContestController(contestService)
	submissionService := service.NewSubmissionService(submissionRepo, userRepo, problemRepo, store, cacheCache, mqMQ, languageService)
	submissionController := handler.NewSubmissionController(submissionService, contestService, mqMQ)
	postRepo := repository.NewPostRepo(db)
	postService := service.NewPostService(postRepo, userRepo, problemRepo, notificationService)
	postController := handler.NewPostController(postService)
	sessionSession := session.New(client)
	tokenService := service.NewTokenService(sessionSession)
	mailer := mail.NewMailer()
	verifyService := service.NewVerifyService(cacheCache, mailer, userRepo)
	userService := service.NewUserService(userRepo, submissionRepo, problemRepo, cacheCache, tokenService, verifyService)
	captchaService := service.NewCaptchaService(cacheCache)
	userController := handler.NewUserController(userService, submissionService, verifyService, captchaService, tokenService)
	uploadController := handler.NewUploadController()
	adminController := handler.NewAdminController(userService)
	remoteAccountRepo := repository.NewRemoteAccountRepo(db)
	remoteService := service.NewRemoteService(remoteAccountRepo)
	remoteController := handler.NewRemoteController(remoteService)
	notificationController := handler.NewNotificationController(notificationService)
	problemSetRepo := repository.NewProblemSetRepo(db)
	problemSetService := service.NewProblemSetService(problemSetRepo, problemRepo, submissionRepo, userRepo)
	problemSetController := handler.NewProblemSetController(problemSetService)
	teamRepo := repository.NewTeamRepo(db)
	teamService := service.NewTeamService(teamRepo, userRepo)
	teamController := handler.NewTeamController(teamService)
	homeworkRepo := repository.NewHomeworkRepo(db)
	homeworkService := service.NewHomeworkService(homeworkRepo, teamRepo, problemRepo, submissionRepo, userRepo, teamService, cacheCache, mqMQ, store, languageService)
	homeworkController := handler.NewHomeworkController(homeworkService)
	agentRepo := repository.NewAgentRepo(db)
	llmClient := llm.NewClient()
	agentService := service.NewAgentService(agentRepo, problemRepo, homeworkService, cacheCache, llmClient)
	agentController := handler.NewAgentController(agentService)
	languageController := handler.NewLanguageController(languageService)
	httpServer := router.NewHttpServer(problemController, contestController, submissionController, postController, userController, uploadController, adminController, remoteController, notificationController, problemSetController, teamController, homeworkController, agentController, languageController, tokenService, cacheCache)
	return httpServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
